import 'package:magazine_luiza/model/product.dart';

List<Product> products = [
  Product(
    photo: "assets/images/celular.jpg",
    name: "Smartphone Samsung Galaxy A71 128GB Azul 6GB RAM",
    description: "Tela 6,7 Câm. Quádrupla + Selfie 32MP",
    price: 1979.97,
    installments: 10,
    installmentsValue: 197.99,
    interest: "sem juros",
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/geladeira.jpg",
    name: "Geladeira Brastemp Frost Free Duplex Evox",
    description: "375L BRM45 HKANA",
    price: 2698.00,
    installments: 10,
    installmentsValue: 269.80,
    interest: "sem juros",
    isFavorite: false,
  ),
  Product(
    photo: "assets/images/fritadeira.jpg",
    name: "Fritadeira Elétrica sem Óleo/Air Fryer Nell Smart",
    description: "Preta 2,4L com Timer",
    price: 229.90,
    installments: 5,
    installmentsValue: 45.98,
    interest: "sem juros",
    isFavorite: false,
  ),
  Product(
    photo: "assets/images/computador.jpg",
    name: "PC Gamer Neologic Start NLI81426 Ryzen 3 2200G 8GB",
    description: "Randeon Vega 8 Integrado + SSD 240GB",
    price: 4859.00,
    installments: 12,
    installmentsValue: 404.92,
    interest: "sem juros",
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/microfone.jpg",
    name: "Microfone de Mesa Condensador para Celular,Computador e Notebook",
    description: "Redshock",
    price: 99.90,
    installments: 3,
    installmentsValue: 33.30,
    interest: "sem juros",
    isFavorite: false,
  ),
  Product(
    photo: "assets/images/ventilador.jpg",
    name: "Ventilador de Parede e Mesa Mondial Maxi Power",
    description: "NV-15-6P-FB 30cm 3 Velocidades",
    price: 89.90,
    installments: 2,
    installmentsValue: 44.95,
    interest: "sem juros",
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/drone.jpg",
    name: "Drone Multilaser Eagle FPV",
    description: "Câmera HD Flips 360",
    price: 2222.00,
    installments: 12,
    installmentsValue: 185.16,
    interest: "sem juros",
    isFavorite: false,
  ),
];
